const DATA_ROOT='https://raw.githubusercontent.com/LGRSV/vera-trechos/main/';
const M=L.map('map').setView([-9.8,-48.5],7),T={sat:L.tileLayer('https://mt{s}.google.com/vt/lyrs=y&x={x}&y={y}&z={z}',{subdomains:['0','1','2','3'],maxZoom:21}),rua:L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19})};T.sat.addTo(M);let base='sat';
const G={t1:L.layerGroup().addTo(M),t2:L.layerGroup().addTo(M),t3:L.layerGroup().addTo(M),ctx:L.layerGroup().addTo(M),cont:L.layerGroup().addTo(M),ch:L.layerGroup().addTo(M),tr:L.layerGroup().addTo(M),alvo:L.layerGroup().addTo(M),fim:L.layerGroup().addTo(M),sel:L.layerGroup().addTo(M),pts:L.layerGroup().addTo(M)},ON={t1:1,t2:1,t3:1,ctx:1,cont:1,ch:1,tr:1,alvo:1,fim:1},ST={T1:['#FFD600',2.7,.95,'t1'],T2:['#00E5FF',1.9,.9,'t2'],T3:['#AB47BC',1.7,.9,'t3']};
let IX={},NA=[],DATA={},PRE={},CURRENT='',INI=null,FIM=null,PICKED=[],MARKERS={},ready=false;
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),digits=x=>String(x??'').replace(/\D/g,''),last8=x=>{let d=digits(x);return d.length>8?d.slice(-8):d},same=(a,b)=>{a=digits(a);b=digits(b);return!!a&&!!b&&(a===b||(a.length>=8&&b.length>=8&&a.slice(-8)===b.slice(-8)))},dist=(a,b)=>{let r=Math.PI/180,x=(b[0]-a[0])*111320*Math.cos((a[1]+b[1])*r/2),y=(b[1]-a[1])*110540;return Math.hypot(x,y)},length=p=>p.slice(1).reduce((s,v,i)=>s+dist(p[i],v),0),quote=x=>'"'+String(x??'').replace(/"/g,'""')+'"';
function toast(x){let t=$('toast');if(!t){t=document.createElement('div');t.id='toast';t.style.cssText='position:fixed;bottom:28px;left:50%;transform:translateX(-50%);background:#252525;color:#fff;padding:9px 14px;border:1px solid #555;border-radius:7px;z-index:9999;font-size:12px';document.body.append(t)}t.textContent=x;t.hidden=false;clearTimeout(t._t);t._t=setTimeout(()=>t.hidden=true,3400)}
function download(n,s,tp){let a=document.createElement('a'),u=URL.createObjectURL(new Blob([s],{type:tp}));a.href=u;a.download=n;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),900)}
function asPoint(o){return Array.isArray(o)?{id:o[0],x:+o[1],y:+o[2]}:{id:o?.nome??o?.codigo??o?.id??'',x:+(o?.lon??o?.longitude),y:+(o?.lat??o?.latitude)}}
function prep(c,d){if(PRE[c])return PRE[c];let seg=[];[['T1',d.t1||[]],['T2',d.t2||[]],['T3',d.t3||[]]].forEach(([t,a])=>a.forEach((p,i)=>{p=(p||[]).map(q=>[+q[0],+q[1]]).filter(q=>isFinite(q[0])&&isFinite(q[1]));if(p.length>1){let xs=p.map(q=>q[0]),ys=p.map(q=>q[1]);seg.push({id:t+'_'+i,t,p,l:length(p),bb:[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)]})}}));let xs=seg.flatMap(s=>[s.bb[0],s.bb[2]]),ys=seg.flatMap(s=>[s.bb[1],s.bb[3]]);return PRE[c]={c,d,seg,bb:[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)],g:null}}
function graph(c){let P=prep(c,DATA[c]);if(P.g)return P.g;let e=P.seg.map(s=>({...s})),n=[],grid=new Map(),a=[],deg=[],cell=.00018;
 const node=p=>{let gx=Math.floor(p[0]/cell),gy=Math.floor(p[1]/cell),best=-1,bv=1e9;for(let i=-1;i<=1;i++)for(let j=-1;j<=1;j++)for(let k of(grid.get((gx+i)+'|'+(gy+j))||[])){let v=dist(p,[n[k].x,n[k].y]);if(v<bv)bv=v,best=k}if(best>=0&&bv<20)return best;let z=n.length;n.push({x:p[0],y:p[1]});a[z]=[];deg[z]=0;let q=gx+'|'+gy;grid.set(q,[...(grid.get(q)||[]),z]);return z};
 e.forEach((s,i)=>{s.a=node(s.p[0]);s.b=node(s.p.at(-1));a[s.a].push(i);a[s.b].push(i);deg[s.a]++;deg[s.b]++});
 let comp=Array(n.length).fill(-1),groups=[];for(let i=0;i<n.length;i++)if(comp[i]<0){let id=groups.length,q=[i],nodes=[];comp[i]=id;while(q.length){let u=q.pop();nodes.push(u);for(let ei of a[u]){let s=e[ei],v=s.a===u?s.b:s.a;if(comp[v]<0){comp[v]=id;q.push(v)}}}groups.push(nodes)}
 const ends=[];groups.forEach((ns,g)=>ns.filter(i=>deg[i]===1).forEach(i=>ends.push({i,g,x:n[i].x,y:n[i].y})));const cg=new Map(),cs=.012;ends.forEach(z=>{let k=Math.floor(z.x/cs)+'|'+Math.floor(z.y/cs);cg.set(k,[...(cg.get(k)||[]),z])});let cand=[],seen=new Set();for(let z of ends){let gx=Math.floor(z.x/cs),gy=Math.floor(z.y/cs);for(let i=-1;i<=1;i++)for(let j=-1;j<=1;j++)for(let w of(cg.get((gx+i)+'|'+(gy+j))||[])){if(z.g===w.g)continue;let k=z.i<w.i?z.i+'|'+w.i:w.i+'|'+z.i;if(seen.has(k))continue;seen.add(k);let d=dist([z.x,z.y],[w.x,w.y]);if(d<=1500)cand.push({z,w,d})}}
 cand.sort((x,y)=>x.d-y.d);let parent=groups.map((_,i)=>i),root=x=>{while(parent[x]!==x){parent[x]=parent[parent[x]];x=parent[x]}return x},v=0;for(let z of cand){let x=root(z.z.g),y=root(z.w.g);if(x===y)continue;parent[x]=y;let id=e.length;e.push({id:'CONT_'+(++v),t:'CONT',p:[[z.z.x,z.z.y],[z.w.x,z.w.y]],l:z.d,a:z.z.i,b:z.w.i,virtual:true,bb:[Math.min(z.z.x,z.w.x),Math.min(z.z.y,z.w.y),Math.max(z.z.x,z.w.x),Math.max(z.z.y,z.w.y)]});a[z.z.i].push(id);a[z.w.i].push(id)}
 return P.g={e,n,a,deg,continuities:v}}
function near(c,x,y){let g=graph(c),best=-1,bv=1e9;g.n.forEach((q,i)=>{let d=dist([x,y],[q.x,q.y]);if(d<bv)bv=d,best=i});return bv<=150?best:-1}
function tog(k){ON[k]=!ON[k];$('btn-'+k)?.classList.toggle('on',!!ON[k]);ON[k]?M.addLayer(G[k]):M.removeLayer(G[k]);if(k==='ctx')updateContext()}
function baseMap(){M.removeLayer(T[base]);base=base==='sat'?'rua':'sat';T[base].addTo(M);$('btn-base').textContent=base==='sat'?'Mapa':'Satélite'}
function list(f=''){f=String(f).toLowerCase();let d=digits(f),L=$('lista'),A=Object.entries(IX).filter(([k,v])=>!f||k.toLowerCase().includes(f)||String(v.se||'').toLowerCase().includes(f)||String(v.circ||'').toLowerCase().includes(f)||(d&&last8(k).includes(d))).sort();$('st').textContent=ready?A.length+' ativos':'Carregando dados...';L.innerHTML='<div class="group">ATIVOS DE REFERÊNCIA</div>';A.forEach(([k,v])=>{let x=document.createElement('div');x.className='it';x.innerHTML='<i class="'+(CURRENT===v.circ?'loaded':'')+'"></i><span><strong>'+esc(k)+'</strong><small>'+esc(v.se||'')+' · '+esc(v.circ||'')+'</small></span>';x.onclick=()=>open(k);L.append(x)});if(NA.length){let h=document.createElement('div');h.className='group';h.textContent='SEM VÍNCULO';L.append(h);NA.filter(k=>!f||String(k).toLowerCase().includes(f)||(d&&last8(k).includes(d))).forEach(k=>{let x=document.createElement('div');x.className='it dimrow';x.innerHTML='<i class="dim"></i><span><strong>'+esc(k)+'</strong><small>Busca pelos últimos 8 dígitos</small></span>';x.onclick=()=>{let m=Object.keys(IX).find(a=>same(a,k));m?open(m):toast('Não localizado no índice atual.')};L.append(x)})}}
function clearMain(){['t1','t2','t3','cont','ch','tr','alvo','fim','sel','pts'].forEach(k=>G[k].clearLayers());MARKERS={};PICKED=[];INI=FIM=null}
function open(k){if(!ready)return;let v=IX[k];if(!v||!DATA[v.circ])return toast('Alimentador não localizado.');clearMain();CURRENT=v.circ;let g=graph(CURRENT),P=prep(CURRENT,DATA[CURRENT]);g.e.forEach((s,i)=>drawSegment(s,i));drawPoints();let m=MARKERS[k];if(m){M.setView([+v.lat,+v.lon],15);setTimeout(()=>m.openPopup(),100)}else M.fitBounds(L.latLngBounds([[P.bb[1],P.bb[0]],[P.bb[3],P.bb[2]]]));bar();box();list($('busca').value);updateContext();if(g.continuities)toast(g.continuities+' continuidade(s) estimada(s) até 1,5 km.')}
function drawSegment(s,i){if(s.virtual){let l=L.polyline(s.p.map(q=>[q[1],q[0]]),{color:'#ffab00',weight:1.5,opacity:.9,dashArray:'7 7'}).addTo(G.cont);l.bindTooltip('Continuidade estimada · '+Math.round(s.l)+' m');l.on('click',()=>one(i));return}let z=ST[s.t],l=L.polyline(s.p.map(q=>[q[1],q[0]]),{color:z[0],weight:z[1],opacity:z[2]}).addTo(G[z[3]]);l.on('click',()=>one(i))}
function pnt(o){let r=document.createElement('div');r.innerHTML='<strong>'+esc(o.id)+'</strong><small>'+esc(o.kind)+' · '+esc(o.circ)+'</small>';let z=document.createElement('div');z.className='pb';[['Início',()=>start(o),''],['Fim',()=>end(o),'f'],['Trecho inicial',()=>{start(o);setTimeout(first,0)},'x'],['Até o final',()=>{start(o);setTimeout(last,0)},'x']].forEach(([t,f,c])=>{let b=document.createElement('button');b.textContent=t;b.className=c;b.onclick=f;z.append(b)});r.append(z);return r}
function drawPoints(){let d=DATA[CURRENT],ref=Object.entries(IX).filter(([,v])=>v.circ===CURRENT);(d.chaves||[]).map(asPoint).filter(q=>isFinite(q.x)&&isFinite(q.y)).forEach(q=>{let z=ref.find(([k,v])=>same(k,q.id)),o={circ:CURRENT,id:z?z[0]:q.id,kind:z?'Ativo':'Chave',x:q.x,y:q.y},m=L.circleMarker([o.y,o.x],{radius:z?8:4.4,fillColor:z?'#ff1744':'#7e57c2',color:'#fff',weight:1.5,fillOpacity:1}).bindPopup(pnt(o)).addTo(z?G.alvo:G.ch);if(z)MARKERS[z[0]]=m});(d.trafos||[]).map(asPoint).filter(q=>isFinite(q.x)&&isFinite(q.y)).forEach(q=>{let o={circ:CURRENT,id:q.id,kind:'Transformador',x:q.x,y:q.y};L.circleMarker([o.y,o.x],{radius:3.7,fillColor:'#1e88e5',color:'#fff',weight:1.2,fillOpacity:1}).bindPopup(pnt(o)).addTo(G.tr)});ref.forEach(([k,v])=>{if(MARKERS[k])return;let o={circ:CURRENT,id:k,kind:'Ativo',x:+v.lon,y:+v.lat};if(isFinite(o.x)&&isFinite(o.y))MARKERS[k]=L.circleMarker([o.y,o.x],{radius:8,fillColor:'#ff1744',color:'#fff',weight:2}).bindPopup(pnt(o)).addTo(G.alvo)});let g=graph(CURRENT);g.n.forEach((n,i)=>{if(g.deg[i]===1){let o={circ:CURRENT,id:'Final '+(i+1),kind:'Final de rede',x:n.x,y:n.y};L.circleMarker([o.y,o.x],{radius:3.5,fillColor:'#ce93d8',color:'#fff',weight:1}).bindPopup(pnt(o)).addTo(G.fim)}})}
function start(o){let n=near(o.circ,o.x,o.y);if(n<0)return toast('Ponto não associado à rede.');INI={...o,n};if(FIM&&FIM.circ!==o.circ)FIM=null;mark();box();M.closePopup()}
function end(o){let n=near(o.circ,o.x,o.y);if(n<0)return toast('Ponto não associado à rede.');if(INI&&INI.circ!==o.circ)return toast('Início e fim devem estar no mesmo alimentador.');FIM={...o,n};mark();box();M.closePopup();if(INI)between()}
function mark(){G.pts.clearLayers();if(INI)L.circleMarker([INI.y,INI.x],{radius:8,fillColor:'#66bb6a',color:'#fff',weight:2}).addTo(G.pts);if(FIM)L.circleMarker([FIM.y,FIM.x],{radius:8,fillColor:'#ce93d8',color:'#fff',weight:2}).addTo(G.pts)}
function box(){let s=$('sel');s.hidden=!CURRENT;$('si').textContent=INI?INI.kind+' '+INI.id:'não definido';$('sf').textContent=FIM?FIM.kind+' '+FIM.id:'não definido';$('be').disabled=!(INI&&FIM);$('bi').disabled=!INI;$('bf').disabled=!INI;$('bc').disabled=!PICKED.length;$('bk').disabled=!PICKED.length}
function dijkstra(a){let g=graph(CURRENT),d=Array(g.n.length).fill(Infinity),pn=Array(g.n.length).fill(-1),pe=Array(g.n.length).fill(-1),q=[];const push=x=>{q.push(x);for(let i=q.length-1;i;){let p=(i-1)>>1;if(q[p][0]<=x[0])break;q[i]=q[p];i=p}q[i]=x},pop=()=>{let r=q[0],x=q.pop();if(q.length){let i=0;while(i*2+1<q.length){let c=i*2+1;if(c+1<q.length&&q[c+1][0]<q[c][0])c++;if(q[c][0]>=x[0])break;q[i]=q[c];i=c}q[i]=x}return r};d[a]=0;push([0,a]);while(q.length){let [w,u]=pop();if(w!==d[u])continue;for(let i of g.a[u]){let s=g.e[i],v=s.a===u?s.b:s.a,z=w+s.l;if(z<d[v])d[v]=z,pn[v]=u,pe[v]=i,push([z,v])}}return{d,pn,pe}}
function path(a,b){let r=dijkstra(a),z=[];if(!isFinite(r.d[b]))return null;for(let x=b;x!==a;x=r.pn[x]){let e=r.pe[x];if(e<0)return null;z.push(e)}return z.reverse()}
function pick(ids,title){let g=graph(CURRENT);ids=[...new Set(ids)].sort((a,b)=>a-b);if(!ids.length)return toast('Nenhum trecho encontrado.');G.sel.clearLayers();PICKED=ids.map(i=>g.e[i]);PICKED.forEach(s=>L.polyline(s.p.map(q=>[q[1],q[0]]),{color:'#00e676',weight:s.virtual?3.1:4.1,dashArray:s.virtual?'7 7':null}).addTo(G.sel));M.fitBounds(L.latLngBounds(PICKED.flatMap(s=>s.p.map(q=>[q[1],q[0]]))),{padding:[35,35]});box();toast(title+': '+PICKED.length+' segmento(s).')}
function between(){if(!(INI&&FIM&&INI.circ===FIM.circ))return toast('Defina início e fim no mesmo alimentador.');let p=path(INI.n,FIM.n);p?.length?pick(p,'Entre início e fim'):toast('Não existe caminho contínuo entre os pontos.')}
function first(){if(!INI)return;pick(graph(CURRENT).a[INI.n]||[],'Trecho inicial')}
function last(){if(!INI)return;let g=graph(CURRENT),r=dijkstra(INI.n),best=-1,bd=-1;g.n.forEach((n,i)=>{if(g.deg[i]===1&&isFinite(r.d[i])&&r.d[i]>bd)bd=r.d[i],best=i});if(best<0)return toast('Final de rede não encontrado.');let n=g.n[best];FIM={circ:CURRENT,id:'Final mais distante',kind:'Final de rede',x:n.x,y:n.y,n:best};mark();pick(path(INI.n,best),'Do início ao final')}
function all(){if(!CURRENT)return toast('Selecione um ativo e carregue o alimentador.');pick(graph(CURRENT).e.map((_,i)=>i),'Todos os trechos')}
function one(i){pick([i],'Trecho individual')}
function clearSel(){PICKED=[];INI=FIM=null;G.sel.clearLayers();G.pts.clearLayers();box()}
function outCSV(){let d=DATA[CURRENT],h=['ALIMENTADOR','SE','POLO','ORDEM','TIPO_REDE','ID_SEGMENTO','COMPRIMENTO_M','INICIO','FIM','GEOMETRIA_WKT','OBSERVACAO'],rows=[h];PICKED.forEach((s,i)=>rows.push([CURRENT,d.se||'',d.polo||'',i+1,s.t,s.id,s.l.toFixed(2),INI?.id||'',FIM?.id||'','LINESTRING ('+s.p.map(q=>q[0].toFixed(7)+' '+q[1].toFixed(7)).join(', ')+')',s.virtual?'Continuidade estimada entre lacunas do mesmo alimentador':'']));download('trechos_'+CURRENT+'.csv','\uFEFF'+rows.map(r=>r.map(quote).join(';')).join('\n'),'text/csv')}
function outKML(){let s='<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document>';PICKED.forEach((e,i)=>s+='<Placemark><name>'+e.t+' '+(i+1)+'</name><description>'+(e.virtual?'Continuidade estimada':'Trecho cadastrado')+'</description><LineString><coordinates>'+e.p.map(q=>q[0]+','+q[1]+',0').join(' ')+'</coordinates></LineString></Placemark>');download('trechos_'+CURRENT+'.kml',s+'</Document></kml>','application/vnd.google-earth.kml+xml')}
function visible(bb,b){return bb[2]>=b[0]&&bb[0]<=b[2]&&bb[3]>=b[1]&&bb[1]<=b[3]}
let ctxTimer;function updateContext(){clearTimeout(ctxTimer);ctxTimer=setTimeout(()=>{G.ctx.clearLayers();if(!CURRENT||!ON.ctx||!ready)return;let b=M.getBounds(),pad=.025,bb=[b.getWest()-pad,b.getSouth()-pad,b.getEast()+pad,b.getNorth()+pad];Object.keys(DATA).filter(c=>c!==CURRENT).forEach(c=>{let P=prep(c,DATA[c]);if(!visible(P.bb,bb))return;P.seg.forEach(s=>{if(visible(s.bb,bb))L.polyline(s.p.map(q=>[q[1],q[0]]),{color:'#777',weight:1.05,opacity:.5,interactive:false}).addTo(G.ctx)})})},220)}
function bar(){let v=CURRENT?DATA[CURRENT]:null;$('bar').innerHTML=v?'<b>'+CURRENT+'</b> · '+esc(v.se||'')+'<br><span style="color:#aaa">Cinza: trechos de outros alimentadores próximos à área visível.</span>':'Nenhum alimentador carregado'}
M.on('moveend',updateContext);
Promise.all([fetch(DATA_ROOT+'indice.json').then(r=>r.json()),fetch(DATA_ROOT+'dados_mapa.json').then(r=>r.json())]).then(([i,d])=>{IX=i.chaves||{};NA=i.nao_encontradas||[];DATA=d||{};Object.entries(DATA).forEach(([c,v])=>prep(c,v));ready=true;list();toast('Dados carregados. Selecione um ativo para abrir o alimentador.')}).catch(()=>{$('st').textContent='Falha ao carregar dados';toast('Não foi possível carregar a base de dados.')});
